### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by abd3lraouf** [willianjusten/will-jekyll-template#52]
I was trying to upload the site to gitlab but in vain.

Here is `.gitlab-ci.yml`
```yml
image: node:8.2.1

before_script:
  - npm install jekyll
  - npm install --global gulp
  - npm link gulp
  - npm install

cache:
  paths:
   - node_modules/

pages:
  stage: deploy
  script:
   - gulp --color --gulpfile ./gulpfile.js
  artifacts:
    paths:
    - public
  only:
   - master
```

there always an error :

```
Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
